id: P000563
initial_creation_type: ocr
source_metadata:
  id: bdr:W21805
  title: སྔོན་འགྲོའི་ཁྲིད་ཡིག་བཀའ་ལུང་རྒྱ་མཚོ
  author: ''
  volumes:
    0872224a8b724eb5bd64de3e41996981:
      image_group_id: I4252
      title: ''
      volume_number: 1
      total_pages: 584
      base_file: v001.txt
ebook_metadata:
  title: སྔོན་འགྲོའི་ཁྲིད་ཡིག་བཀའ་ལུང་རྒྱ་མཚོ
  author: ''
  sku: P000563
  cover: cover.jpg
  layers:
  - pagination
